Web_BachLongMobile/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_TMDT.Models;
using System.IO;
using PagedList.Mvc;
using PagedList;
using Web_TMDT.Common;
using System.ComponentModel.DataAnnotations;
using Excel = Microsoft.Office.Interop.Excel;
using System.Runtime.InteropServices;

namespace Web_TMDT.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        HTTT_DoanhNghiepEntities db = new HTTT_DoanhNghiepEntities();
        public ActionResult Index()
        {
            return View();
        }
        #region Đăng nhập
        //Đăng nhập Admin
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection f)
        {

            if (f["ten"] == "" || f["pass"] == "")
            {
                ViewBag.thongbao = "Tên Đăng nhập hoặc Mật Khẩu không được trống!!!";
                return View("Dangnhap");
            }
            else
            {
                var ad = Dangnhap(f["ten"], f["pass"]);
                if (ad == 0)
                {
                    ViewBag.thongbao = "Tên đăng nhập hoặc mật khẩu không đúng!!!";
                    return View("Dangnhap");
                }
                else if (ad == 1)
                {
                    Session["admin"] = f["ten"];
                    return View("Index");
                }
                else if (ad == 2)
                {
                    Session["NguoiBan"] = f["ten"];
                    return View("Index");
                }
                else
                {
                    ViewBag.thongbao = "Mật khẩu không đúng!!!";
                    return View("Dangnhap");
                }
            }
        }
        public int Dangnhap(string ten, string pass)
        {
            var kq = db.Users.SingleOrDefault(n => n.UserName == ten) ;
            if (kq == null)
            {
                return 0;
            }
            else
            {
                if (kq.Password == HamMaHoaPass.MD5Hash(pass) && kq.IDTrangThaiUser == 3)
                {
                    //đăng nhập đúng
                    return 1;
                }
                if (kq.Password == HamMaHoaPass.MD5Hash(pass) && kq.IDTrangThaiUser == 4)
                {
                    //đăng nhập đúng
                    return 2;
                }
                else
                {
                    //đăng nhập sai mk
                    return -1;
                }
            }
        }


        public ActionResult Logout()
        {
            Session["admin"] = null;
            Session["NguoiBan"] = null;
            return RedirectToAction("Index");
        }
        #endregion


        #region QL Bài Đăng
        public ActionResult QLBaiDang(int? page)
        {
            
            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                        return View("Index");

                }
            }
            
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            List<BaiDang> bd = (from n in db.BaiDangs orderby (n.SoLuong - n.Soluongton) descending select n).ToList();
            return View(bd.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult SapXepGiamdan(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            List<BaiDang> b = (from bd in db.BaiDangs orderby bd.DanhGia descending select bd).ToList();
            return View(b.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult CapnhatSL(int id)
        {
            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }
            BaiDang bd = db.BaiDangs.SingleOrDefault(n => n.MaSanPham == id);
            return View(bd);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CapnhatSL(int id, FormCollection f)
        {

            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }
            BaiDang bd = db.BaiDangs.SingleOrDefault(n => n.MaSanPham == id);

            
            bd.SoLuong = bd.SoLuong + int.Parse(f["slthem"].ToString());
            bd.Soluongton = bd.Soluongton + int.Parse(f["slthem"].ToString());
            //bd.SoLuong = int.Parse(f["sldang"].ToString());
            //bd.Soluongton = int.Parse(f["slton"].ToString());
            db.SaveChanges();
            return RedirectToAction("QLBaiDang");
        }

        [HttpGet]
        public ActionResult SuaSP(int id)
        {
            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }
            BaiDang bd = db.BaiDangs.SingleOrDefault(n => n.MaSanPham == id);
            ViewBag.Loai = new SelectList(db.LoaiSanPhams.ToList(), "MaLoai", "TenLoai", bd.MaLoai );
            return View(bd);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaSP(int id, FormCollection f)
        {
            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }
            BaiDang bd = db.BaiDangs.SingleOrDefault(n => n.MaSanPham == id);           

            bd.TenSP = f["tensp"].ToString();
            //bd.Soluongton = int.Parse(f["sl"].ToString());
            bd.MaLoai = int.Parse(f["Loai"].ToString());
            bd.GiaSP = int.Parse(f["giasp"].ToString());
            bd.MoTa = f["mota"].ToString();
            db.SaveChanges();

            ViewBag.Loai = new SelectList(db.LoaiSanPhams.ToList(), "MaLoai", "TenLoai", bd.MaLoai);
            return RedirectToAction("QLBaiDang");
        }


         [HttpGet]
        public ActionResult CapNhatTT(int id)
        {
            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }
            BaiDang bd = db.BaiDangs.SingleOrDefault(n => n.MaSanPham == id);
            ViewBag.IDTrangThai = new SelectList(db.TrangThaiBaiDangs.ToList(), "IDTrangThai", "TenTrangThai", bd.IDTrangThai);
            return View(bd);
        }
         [HttpPost]
        [ValidateInput(false)]
        public ActionResult CapNhatTT(int id,FormCollection f)
        {
            if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }
            BaiDang bd = db.BaiDangs.SingleOrDefault(n => n.MaSanPham == id);
            bd.IDTrangThai = int.Parse(f["IDTrangThai"].ToString());
          
            db.SaveChanges();
            ViewBag.IDTrangThai = new SelectList(db.TrangThaiBaiDangs.ToList(), "IDTrangThai", "TenTrangThai", bd.IDTrangThai);
            return RedirectToAction("QLBaiDang");
        }
       

        #endregion
         public ActionResult QLUser(int? page)
        {
            if (Session["NguoiBan"] != null)
            {
                return Content("<script language='javascript' type='text/javascript'>alert('Xin Lỗi! Bạn Không Có Quyền Vào Trang Này');window.location.href='../Admin/Index';</script>");
            }
            else if (Session["admin"] == null)
            {
                if (Session["NguoiBan"] == null)
                {
                    return View("Index");

                }
            }

            
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            List<User> user = db.Users.ToList();
            return View(user.ToPagedList(pageNumber, pageSize));
        }

         [HttpGet]
        
         public ActionResult ThemUser()
         {

             if (Session["NguoiBan"] != null)
             {
                 return Content("<script language='javascript' type='text/javascript'>alert('Xin Lỗi! Bạn Không Có Quyền Vào Trang Này');window.location.href='../Admin/Index';</script>");
             }
             else if (Session["admin"] == null)
             {
                 if (Session["NguoiBan"] == null)
                 {
                     return View("Index");

                 }
             }
             return View();
         }
         [HttpPost]
         [ValidateInput(false)]
        public ActionResult ThemUser(RegisterModel model)
         {
             if (Session["NguoiBan"] != null)
             {
                 return Content("<script language='javascript' type='text/javascript'>alert('Xin Lỗi! Bạn Không Có Quyền Vào Trang Này');window.location.href='../Admin/Index';</script>");
             }
             else if (Session["admin"] == null)
             {
                 if (Session["NguoiBan"] == null)
                 {
                     return View("Index");

                 }
             }
             //Nếu đầy đủ thông tin hợp lệ
             if (ModelState.IsValid)
             {
                 if (CheckUserName(model.Username))
                 {
                     // ModelState.AddModelError("","Tên người dùng đã tồn tại");
                     return Content("<script language='javascript' type='text/javascript'>alert('Tài khoản đã tồn tại ');window.location.href='../Admin/ThemUser';</script>");
                 }
                 else
                 {
                     var user = new User();

Web_BachLongMobile/Controllers/SPMoiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_TMDT.Models;
using PagedList.Mvc;
using PagedList;

namespace Web_TMDT.Controllers
{
    public class SPMoiController : Controller
    {
        //
        // GET: /SPMoi/
        HTTT_DoanhNghiepEntities db = new HTTT_DoanhNghiepEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SPMoi(int? page)
        {
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            var bd = (from s in db.BaiDangs
                     where s.IDTrangThai == 2 && s.Soluongton > 0
                      orderby s.GiaSP descending
                     select s).ToList();
            return View(bd.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult CTSP(int masp)
        {
            List<DanhGiaSanPham> dem = new List<DanhGiaSanPham>();
            dem = db.DanhGiaSanPhams.Where(n => n.MaSanPham == masp).ToList();
            int tong = dem.Count;
            var sp = (from bd in db.BaiDangs.ToList()
                      //from dg in db.ChiTietDanhGiaNguoiMuas.ToList()
                      where bd.MaSanPham == masp
                      select new ChiTietSanPham()
                      {
                          MaSP = bd.MaSanPham,
                          hinhanh = bd.HinhAnh,
                          TenSP = bd.TenSP,
                          GiaSP = bd.GiaSP,
                          SoLuongTon = bd.Soluongton,
                          MoTa = bd.MoTa,
                          DemNguoiDG = tong,
                          DiemDG = Convert.ToInt32(bd.DanhGia)
                      }).ToList();

            return View(sp);
        }

        public ActionResult SanPham(int? page)
        {
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            var bd = (from s in db.BaiDangs
                      where s.IDTrangThai == 2 && s.Soluongton > 0
                      orderby s.GiaSP descending
                      select s).ToList();
            return View(bd.ToPagedList(pageNumber, pageSize));
        }
	}
}

Web_BachLongMobile/Views/LayOut/LayOutNguoiDung.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/LayOut/fonts.css" rel="stylesheet" />
    @*<link href="~/Content/LayOut/screen.css" rel="stylesheet" />*@
    <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-4.4.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/css/Site.css" rel="stylesheet" />
    @*ChènQuảngCáo*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.js"></script>
    <script src="~/Scripts/script.js"></script>
    <script src="~/NivoSlider/jquery.nivo.slider.js"></script>
    <script src="~/NivoSlider/jquery.nivo.slider.pack.js"></script>
    <link href="~/NivoSlider/nivo-slider.css" rel="stylesheet" />


    
</head>
<body>
    <section class="headline">
        <div class="container clearfix">            
            <div class="user pull-right">
                @if (Session["Name"] != null)
                {
                    <ul class="menu">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-user fa-fw"></i> @Session["Name"].ToString()
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="~/Users/SuaUser">Thông Tin cá nhân</a>
                                </li>
                                <li>
                                    <a href="~/Users/MK">Đổi Mật Khẩu</a>
                                </li>
                                <li>
                                    <a href="~/BaiDang/ThongTinMuaHang">Thông Tin Mua hàng</a>
                                </li>
                                <li>
                                    @Html.ActionLink("Đăng Xuất", "Logout", "Users", null, htmlAttributes: new { @class = "Users" })
                                </li>
                            </ul>

                            <!-- /.dropdown-user -->
                        </li>
                        <li>@Html.Action("GioHangPartial", "GioHang")</li>                        
                    </ul>

                }
                else
                {                   
                    
                    <ul class="menu">
                        <li>
                            @Html.Action("GioHangPartial", "GioHang")
                        </li>
                        <li>
                            <a href="@Url.Action("Register", "Users")"><i class="fa fa-sign-in"></i> Đăng ký</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Login", "Users")"><i class="fa fa-unlock"></i> Đăng nhập</a>
                        </li>
                    </ul>
                    
                }
            </div>

        </div>
    </section>

    <section class="header">
        <div class="container clearfix">
            <div id="logo" class="pull-left">
                <a href="/">
                    <img src="~/Hinh/logo.png" />
                </a>
            </div>
            <div class="navbar navbar-default pull-right">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Trang chủ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("SanPham", "SPMoi")">Sản phẩm</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")">Giới thiệu</a>
                    </li>
                    <li>
                        <a href="#">Liên hệ</a>
                    </li>
                </ul>
            </div>
        </div>

        @*<div class="flash success" id="divmenu">
            <div id="raovat">
                <div>
                    @Html.Action("GioHangPartial", "GioHang")
                </div>
                
                <i class="fa fa-pencil-square-o"></i>
                @Html.ActionLink("Đăng tin Sản Phẩm", "BaiDang", "BaiDang", null, htmlAttributes: new { @class = "DangTin" })

            </div>
            
            <div class="iconlogo">
                <a href="~/SPMoi/SPMoi">
                    <img src="~/Hinh/iPhone-icon.png" /></a>
                </div>
           
        </div>*@

    </section>

    <section class="QuangCao">
        <div class="container">
            <div id="slider" class="nivoSlider">
                <img src="~/Hinh/aaaa.png" />
                <img src="~/Hinh/bbbbb.png" />
                <img src="~/Hinh/ccccc.png" />
                <img src="~/Hinh/dddd.png" />
            </div>
            <div id="htmlcaption" class="nivo-html-caption">
                <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
            </div>
        </div>
    </section>    

    <section class="main">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="activity">
                        @Html.Action("LoaiSPPartial", "Home")
                    </div>
                </div>
                <div class="col-md-9 main-content">
                    <div id="search">
                        @Html.Action("TimKiem", "Home")
                    </div>
                    <div class="content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="footer">
        <div class="container">    
            <address>
                <p><i class="fa fa-phone"></i> Số điện thoại: 08.35353508</p>
                <p><i class="fa fa-envelope"></i> Email: contact@sgu.edu.vn</p>
                <p><i class="fa fa-map-marker"></i> 273 An Dương Vương, Quận 5, TP.Hồ Chí Minh</p>
            </address>       
                                
               
           
        </div>
    </section>
    
</body>
</html>
<script type="text/javascript">
    $(window).load(function () {
        $('#slider').nivoSlider({

            controlNav: false,
            prevText: '',
            nextText: ''
        });
        
    });
</script>

Web_BachLongMobile/Views/LayOut/LayOutThongtin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/LayOut/fonts.css" rel="stylesheet" />
    @*<link href="~/Content/LayOut/screen.css" rel="stylesheet" />*@
    <link href="~/Content/LayOut/screen.css" rel="stylesheet" />
    <link href="~/Content/LayOut/CssLayout.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-4.4.0/css/font-awesome.min.css" rel="stylesheet" />
    @*ChènQuảngCáo*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/NivoSlider/jquery.nivo.slider.js"></script>
    <script src="~/NivoSlider/jquery.nivo.slider.pack.js"></script>
    <link href="~/NivoSlider/nivo-slider.css" rel="stylesheet" />

    <script src="~/Content/LayOut/JavaScript1.js"></script>


</head>
<body>

    <section class="blank">
        <div class="flash">
            <div class="Dangkydangnhap">
                @if (Session["Name"] != null)
                {
                    <div id="ddd">
                        <a href="~/SPMoi/SPMoi">
                            <img src="~/Hinh/logo.png" />
                        </a>
                    </div>
                    <div id="menu">
                        <ul>
                            <li class="gh">@Html.Action("GioHangPartial", "GioHang")</li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    @Session["Name"].ToString()<i class="fa fa-user fa-fw"></i>

                                </a>

                                <ul id="submenu">
                                    <li>
                                        <a href="~/Users/SuaUser">Thông Tin cá nhân</a>
                                    </li>
                                    <li>
                                        <a href="~/Users/MK">Đổi Mật Khẩu</a>
                                    </li>
                                    <li>
                                        <a href="~/BaiDang/ThongTinMuaHang">Thông Tin Mua hàng</a>
                                    </li>
                                    <li>
                                        @Html.ActionLink("Đăng Xuất", "Logout", "Users", null, htmlAttributes: new { @class = "Users" })
                                    </li>
                                </ul>

                                <!-- /.dropdown-user -->
                            </li>
                        </ul>
                    </div>

                }
                else
                {
                    <div id="bbb">
                        <a href="~/SPMoi/SPMoi">
                            <img src="~/Hinh/logo.png" />
                        </a>
                    </div>
                    @Html.Action("GioHangPartial", "GioHang")

                    <b>
                        <i class="fa fa-sign-in"></i>
                        @Html.ActionLink("Đăng Ký", "Register", "Users", null, htmlAttributes: new { @class = "Users" })
                    </b>
                    <b>
                        <i class="fa fa-unlock"></i>
                        @Html.ActionLink("Đăng Nhập", "Login", "Users", null, htmlAttributes: new { @class = "Users" })
                    </b>
                }
            </div>

        </div>

        @*<div class="flash success" id="divmenu">
                <div id="raovat">
                    <div>
                        @Html.Action("GioHangPartial", "GioHang")
                    </div>

                    <i class="fa fa-pencil-square-o"></i>
                    @Html.ActionLink("Đăng tin Sản Phẩm", "BaiDang", "BaiDang", null, htmlAttributes: new { @class = "DangTin" })

                </div>

                <div class="iconlogo">
                    <a href="~/SPMoi/SPMoi">
                        <img src="~/Hinh/iPhone-icon.png" /></a>
                    </div>

            </div>*@

    </section>

    <section class="QuangCao">
        <div id="slider" class="nivoSlider">
            <img src="~/Hinh/aaaa.png" />
            <img src="~/Hinh/bbbbb.png" />
            <img src="~/Hinh/ccccc.png" />
            <img src="~/Hinh/dddd.png" />
        </div>
        <div id="htmlcaption" class="nivo-html-caption">
            <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
        </div>
    </section>


    <section>
        <div id="menuLoai">
            <div class="activity">
                @Html.Action("LoaiSPPartial", "Home")
            </div>
        </div>
        <div id="noidung">
            <div id="txttimkiem">
                @Html.Action("TimKiemTT", "Home")
            </div>
            <br />
            <br />
            @RenderBody()
        </div>
        <div style="clear:both"></div>
    </section>



    <section>
        <div class="button button-buy">

            <i class="fa fa-phone"></i>: 08.35353508

            <div>
                273 An Dương Vương, Quận 5, TP.Hồ Chí Minh
            </div>

        </div>
    </section>

</body>
</html>
<script type="text/javascript">
    $(window).load(function () {
        $('#slider').nivoSlider({

            controlNav: false,
            prevText: '',
            nextText: ''
        });

    });
</script>

Web_BachLongMobile/Views/LayOut/LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/LayOut/fonts.css" rel="stylesheet" />
    <link href="~/Content/LayOut/CssLayOut.css" rel="stylesheet" />
    <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-4.4.0/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/LayOutAdmin/metisMenu.min.css" rel="stylesheet" />
    <link href="~/Content/css/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.js"></script>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="admin-page">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" id="menungang" role="navigation" style="margin-bottom: 0">
           
            <div class="container-fluid clearfix">
                <div class="pull-left">
                    <h2>Admin</h2>
                </div>
                <div class="pull-right">
                    <ul>
                        <li>
                            <a href="~/Admin/Index">Trang quản lý</a>
                        </li>
                        <li>
                            <a href="/">Trang chủ</a>
                        </li>
                    </ul>
                </div>
                    
                    @*<ul class="menu">
                        <li>
                            <a href="~/Users/SuaUser">Thông Tin cá nhân</a>
                        </li>
                        <li>
                            <a href="@Url.Action("DoiMatKhau", "Admin")">Đổi Mật Khẩu</a>
                        </li>
                        <li>
                            @Html.ActionLink("Đăng Xuất", "Logout", "Users", null, htmlAttributes: new { @class = "Users" })
                        </li>
                    </ul>*@
            </div>
               
                <!-- /.navbar-header -->
                <!-- /.navbar-top-links -->
           
                
               
            
                <!-- /.navbar-static-side -->
            </nav>
        <div class="main-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3 navbar-default sidebar" role="navigation">
                        <div class="sidebar-nav navbar-collapse">
                            <ul class="nav" id="side-menu">
                                <li>
                                    <a href="~/BaiDang/BaiDang"><i class="fa fa-edit"></i> Đăng Tin Sản Phẩm</a>
                                </li>

                                <li>
                                    <a href="~/Admin/QLBaiDang"><i class="fa fa-dashboard fa-fw"></i> Quản Lý Sản Phẩm</a>
                                </li>

                                <li>
                                    <a href="~/Admin/QLUser"><i class="fa fa-user"></i> Quản Lý User</a>
                                </li>
                                @*<li>
                            <a href="~/Admin/DHMua"><i class="fa fa-edit fa-fw"></i> Thông Tin Đơn Hàng Mua</a>
                        </li>*@
                                <li>
                                    <a href="~/Admin/DHMua"><i class="fa fa-table fa-fw"></i> Thống Kê Đơn Hàng</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.sidebar-collapse -->
                    </div>
                    <div class="col-md-9 content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
       
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->


</body>
</html>