Web_BachLongMobile/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_TMDT.Models;
using PagedList;
using PagedList.Mvc;

namespace Web_TMDT.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        HTTT_DoanhNghiepEntities db = new HTTT_DoanhNghiepEntities();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult LoaiSPPartial()
        {
            var hieu = db.LoaiSanPhams.ToList();
            return PartialView(hieu);
        }
        /*dien thoai theo chu de*/
        public ViewResult SPtheo_loai(int maloai, int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            List<BaiDang> listsp = db.BaiDangs.Where(n => n.MaLoai == maloai && n.IDTrangThai == 2 && n.Soluongton > 0).OrderBy(n => n.NgayDang).ToList();
            if (listsp.Count == 0)
            {
                ViewBag.SP = "Không có sản phẩm nào thuộc loại này";
            }
            ViewBag.SP = "Sản Phẩm Cần Tìm!";
            return View(listsp.ToPagedList(pageNumber, pageSize));
            
        }   
        public PartialViewResult TimKiem()
        {
            List<SelectListItem> thang = new List<SelectListItem>();
            for (int i = 0; i <= 30000000; i = i+1000000)
            {
                SelectListItem one = new SelectListItem() { Text = i.ToString(), Value = i.ToString() };
                thang.Add(one);
            }
            ViewBag.thang = thang;
            List<SelectListItem> nam = new List<SelectListItem>();
            int aa = Convert.ToInt32(DateTime.Now.Year);
            for (int i = 0; i <= 30000000; i = i+1000000)
            {
                SelectListItem one = new SelectListItem() { Text = i.ToString(), Value = i.ToString() };
                nam.Add(one);
            }
            ViewBag.nam = nam;
            ViewBag.MaLoai = new SelectList(db.LoaiSanPhams.ToList(), "MaLoai", "TenLoai");
            return PartialView();
        }


        public PartialViewResult TimKiemTT()
        {
            return PartialView();
        }
        public PartialViewResult TimCTDH()
        {
            return PartialView();
        }
        
	}
}

Web_BachLongMobile/Controllers/SPMoiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_TMDT.Models;
using PagedList.Mvc;
using PagedList;

namespace Web_TMDT.Controllers
{
    public class SPMoiController : Controller
    {
        //
        // GET: /SPMoi/
        HTTT_DoanhNghiepEntities db = new HTTT_DoanhNghiepEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SPMoi(int? page)
        {
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            var bd = (from s in db.BaiDangs
                     where s.IDTrangThai == 2 && s.Soluongton > 0
                      orderby s.GiaSP descending
                     select s).ToList();
            return View(bd.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult CTSP(int masp)
        {
            List<DanhGiaSanPham> dem = new List<DanhGiaSanPham>();
            dem = db.DanhGiaSanPhams.Where(n => n.MaSanPham == masp).ToList();
            int tong = dem.Count;
            var sp = (from bd in db.BaiDangs.ToList()
                      //from dg in db.ChiTietDanhGiaNguoiMuas.ToList()
                      where bd.MaSanPham == masp
                      select new ChiTietSanPham()
                      {
                          MaSP = bd.MaSanPham,
                          hinhanh = bd.HinhAnh,
                          TenSP = bd.TenSP,
                          GiaSP = bd.GiaSP,
                          SoLuongTon = bd.Soluongton,
                          MoTa = bd.MoTa,
                          DemNguoiDG = tong,
                          DiemDG = Convert.ToInt32(bd.DanhGia)
                      }).ToList();

            return View(sp);
        }

        public ActionResult SanPham(int? page)
        {
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            var bd = (from s in db.BaiDangs
                      where s.IDTrangThai == 2 && s.Soluongton > 0
                      orderby s.GiaSP descending
                      select s).ToList();
            return View(bd.ToPagedList(pageNumber, pageSize));
        }
	}
}

Web_BachLongMobile/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_TMDT.Models;
using PagedList;
using PagedList.Mvc;

namespace Web_TMDT.Controllers
{
    public class TimKiemController : Controller
    {
        //
        // GET: /TimKiem/
        HTTT_DoanhNghiepEntities db = new HTTT_DoanhNghiepEntities();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult KQTim(int? page, string tim, string loai, string tu, string den)
        {

            @ViewBag.tu = tu;
            @ViewBag.den = den;
            @ViewBag.tim = tim;
            @ViewBag.loai = loai;

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            List<BaiDang> KQTimKiem = new List<BaiDang>();

            if (string.IsNullOrWhiteSpace(tim) && string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                KQTimKiem = (from n in db.BaiDangs
                             where n.IDTrangThai == 2 && n.Soluongton > 0
                             select n).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(tim) && string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                return View();
            }
            else if (!string.IsNullOrWhiteSpace(tim) && string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                KQTimKiem = db.BaiDangs.Where(n => n.TenSP.Contains(tim) && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (!string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                int timloai = int.Parse(loai);
                KQTimKiem = db.BaiDangs.Where(n => n.MaLoai == timloai && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giaden = int.Parse(den);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP <= giaden && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.GiaSP <= giaden && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (!string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                int timloai = int.Parse(loai);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.GiaSP <= giaden && n.MaLoai == timloai && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && !string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.GiaSP <= giaden && n.TenSP.Contains(tim) && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (!string.IsNullOrWhiteSpace(tim) && !string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                int timloai = int.Parse(loai);
                KQTimKiem = db.BaiDangs.Where(n => n.TenSP.Contains(tim) && n.MaLoai == timloai && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                int timloai = int.Parse(loai);
                KQTimKiem = db.BaiDangs.Where(n => n.TenSP.Contains(tim) && n.MaLoai == timloai && n.GiaSP <= giaden && n.GiaSP >= giatu && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }

            if (KQTimKiem.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm cần tìm!";
            }
            return View(KQTimKiem.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult KQTim(int? page, FormCollection f)
        {
            
            string tim = f["txttimkiem"].ToString();           
            string loai = (Request["MaLoai"]).ToString();
            string tu = f["thang"];
            string den = f["nam"];

            @ViewBag.tu = tu;
            @ViewBag.den = den;
            @ViewBag.tim = tim;
            @ViewBag.loai = loai;

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            List<BaiDang> KQTimKiem = new List<BaiDang>();

            if (string.IsNullOrWhiteSpace(tim) && string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                KQTimKiem = (from n in db.BaiDangs
                             where n.IDTrangThai == 2 && n.Soluongton > 0
                             select n).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(tim) && string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                return View();
            }
            else if (!string.IsNullOrWhiteSpace(tim) && string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                KQTimKiem = db.BaiDangs.Where(n => n.TenSP.Contains(tim) && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (!string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                int timloai = int.Parse(loai);
                KQTimKiem = db.BaiDangs.Where(n => n.MaLoai == timloai && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if(string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giaden = int.Parse(den);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP <= giaden && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.GiaSP <= giaden && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (!string.IsNullOrWhiteSpace(loai) && string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                int timloai = int.Parse(loai);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.GiaSP <= giaden && n.MaLoai == timloai && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (string.IsNullOrWhiteSpace(loai) && !string.IsNullOrWhiteSpace(tim) && !string.IsNullOrEmpty(tu) && !string.IsNullOrEmpty(den))
            {
                int giatu = int.Parse(tu);
                int giaden = int.Parse(den);
                KQTimKiem = db.BaiDangs.Where(n => n.GiaSP >= giatu && n.GiaSP <= giaden && n.TenSP.Contains(tim) && n.IDTrangThai == 2 && n.Soluongton > 0).ToList();
                ViewBag.ThongBao = "Sản Phẩm Cần Tìm!";
            }
            else if (!string.IsNullOrWhiteSpace(tim) && !string.IsNullOrWhiteSpace(loai) && string.IsNullOrEmpty(tu) && string.IsNullOrEmpty(den))
            {
                int timloai = int.Parse(loai);

Web_BachLongMobile/Views/Home/Index.cshtml
@{
    Layout = "~/Views/LayOut/LayOutNguoiDung.cshtml";
    ViewBag.Title = "Index";
}

Web_BachLongMobile/Views/Home/LoaiSPPartial.cshtml
@using Web_TMDT.Models;
@model List<LoaiSanPham>
<div class="sidebar" role="navigation">
    <div class="sidebar-nav">
        <h2>Hãng sản xuất</h2>
        <div class="content">
            <ul class="nav" id="side-menu">
                @foreach (var item in Model)
                {
                    <li>
                        <a href="@Url.Action("SPtheo_loai", new { @maloai=item.MaLoai})">@item.TenLoai</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

Web_BachLongMobile/Views/Home/SPtheo_loai.cshtml
@using Web_TMDT.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<BaiDang>
@{
    ViewBag.Title = "SPtheo_loai";
    Layout = "~/Views/LayOut/LayOutNguoiDung.cshtml";
}
@if (Model.Count == 0)
{
    <div class="mmm"><h2>@ViewBag.sp</h2></div>
}
<div class="mmm"><h2>@ViewBag.ThongBao</h2></div>
<div class="spmoiaaa">
    @{int n = 0;}
    @foreach (var item in Model)
    {
        n++;
        <div class="TrangSanPham">
            <div>
                <div class="ten">
                    <a href="@Url.Action("CTSP", "SPMoi", new { @masp = item.MaSanPham})"><label for="male">@item.TenSP</label></a>
                </div>
                <div class="hinh">
                    <a href="@Url.Action("CTSP", "SPMoi", new { @masp = item.MaSanPham })"> <img src="@Url.Content("~/Hinh_anh/"+item.HinhAnh)" width="130" height="160" /> </a>
                </div>

                <div class="giasp">
                    <label for="malea">Giá: @string.Format("{0:0,0}", @item.GiaSP) VNĐ</label>
                </div>
                <div class="slsp">
                    <label for="malea">Số Lượng Còn: @item.Soluongton</label>
                </div>
            </div>
        </div>


        if (n % 3 == 0)
        {
            <div style="clear:both"></div>
            <br />
        }
    }
</div>
<div style="clear:both"></div>
@*tao trang lien ket*@
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    <div class="pt">
        @Html.PagedListPager(Model, page => Url.Action("SPtheo_loai", new { page, maloai = Request.QueryString["maloai"] }))
    </div>

    

Web_BachLongMobile/Views/Home/TimCTDH.cshtml
@*@{
    ViewBag.Title = "TimCTDH";
    Layout = "~/Views/LayOut/TimChiTietDonHang.cshtml";
}*@
@using (Html.BeginForm("KQTimCTDH", "BaiDang"))
{
 
    
<div id="lb">
    <h3 class="tl">Tìm Tên Sản Phẩm:</h3>
</div>   
<div id="tim">    
    @Html.TextBox("txttimkiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Nhập từ khoá cần tìm..." })
</div>
<div id="buttontim">
    <button type="submit"><img src="~/Hinh/search.png" /></button>
</div>
}

Web_BachLongMobile/Views/Home/TimKiem.cshtml
@using (Html.BeginForm("KQTim", "TimKiem"))
{
    @*<div class="timTT">
    <h5 class="qq">Tìm Tên & Loại Sản Phẩm:</h5>
    </div>*@
    <div class="item">
        @Html.DropDownList("thang", "--Giá Từ--")
    </div>
    <div class="item">@Html.DropDownList("nam", "--Giá Đến--")</div>
    <div class="item">       
        @Html.TextBox("txttimkiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Nhập từ khoá cần tìm..." })
    </div>
    <div class="item">@Html.DropDownList("MaLoai", "----Tất Cả Hãng sản xuất----")</div>
    <div class="item action">
       <button class="btn-1">Tìm kiếm <i class="fa fa-search"></i></button>
    </div>
}


    

Web_BachLongMobile/Views/Home/TimKiemTT.cshtml
@using (Html.BeginForm("KQTimDH", "BaiDang"))
{
    
<div class="timTT">
    <h5 class="qq">Tìm Ngày Lập Hóa Đơn:</h5>
</div>
<div class="day1"><input type="date" name="tungay" value="----Chọn Thời gian Bắt đầu------"  /></div>
<div class="day2"><input type="date" name="denngay" value="----Chọn Thời Gian Kết Thúc-----" /></div>

<div id="buttontim">
    <button type="submit"><img src="~/Hinh/search.png" /></button>
</div>
}